Repository GSG-G13/team-4, pull requests merged in 2023-05, with the labels that each got.

#3 File structure
  client/.eslintrc.cjs
  client/.gitignore
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/vite.svg
  client/src/App.css
  client/src/App.jsx
  client/src/assets/react.svg
  client/src/components/Button.jsx
  client/src/components/Card.jsx
  client/src/components/Input.jsx
  client/src/components/Navbar.jsx
  client/src/index.css
  client/src/main.jsx
  client/src/pages/Home.jsx
  client/src/pages/ProductDetails.jsx
  client/src/pages/Shop.jsx
  client/src/pages/Signin.jsx
  client/src/pages/Signup.jsx
  client/src/pages/seller.jsx
  client/vite.config.js
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/controller/product.contrller.js
  server/src/controller/user.controller.js
  server/src/database/config/build.sql
  server/src/database/config/connection.js
  server/src/database/query/product.query.js
  server/src/database/query/user.query.js
  server/src/index.js
  server/src/router/product.router.js
  server/src/router/user.router.js
  server/src/utilis/index.js
  server/src/utilis/validation/schema.js
Labels: approved

#7 build server
  server/.eslintrc.json
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/index.js
  server/src/router/index.js
  server/src/utils/index.js
  server/src/utils/validation/schema.js
Labels: waiting-review

#10 Sign up controller
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  server/src/controller/pages/signUp.js
  server/src/controller/products/product.contrller.js
  server/src/controller/user.js
  server/src/controller/users/user.controller.js
  server/src/database/config/build.sql
  server/src/database/config/connection.js
  server/src/database/query/user.query.js
  server/src/router/index.js
  server/src/router/product.js
  server/src/router/user.js
  server/src/router/user.router.js
  server/src/utilis/validation/schema.js
  server/src/utils/index.js
  server/src/utils/validation/schema.js
Labels: waiting-review

#14 add product
  server/src/controller/products/product.contrller.js
  server/src/database/query/product.query.js
  server/src/router/index.js
  server/src/router/product.router.js
  server/src/router/user.router.js
Labels: approved

#19 Create sign up client 11
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/main.jsx
  client/src/pages/Home.jsx
  client/src/pages/Signup.jsx
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/controller/products/filterProductsByPriceController.js
  server/src/controller/products/getAllProductsController.js
  server/src/controller/products/product.controller.js
  server/src/controller/users/user.controller.js
  server/src/database/config/build.sql
  server/src/database/query/filterPRoductsByPriceQuery.js
  server/src/database/query/getAllProductsQuery.js
  server/src/database/query/user.query.js
  server/src/router/index.js
  server/src/router/product.router.js
  server/src/utilis/validation/schema.js
Labels: done

#21 fix path
  server/src/controller/products/product.js
Labels: done

#23 filter By Price in Backend
  server/src/controller/products/filterProductsByPriceController.js
  server/src/database/query/filterPRoductsByPriceQuery.js
  server/src/router/index.js
  server/src/router/product.router.js
Labels: approved

#30 create auth function
  server/src/database/query/user.query.js
  server/src/utilis/auth/auth.js
Labels: approved

#32 fix auth function
  server/src/controller/users/user.controller.js
  server/src/database/query/user.query.js
  server/src/router/product.router.js
  server/src/utilis/auth/auth.js
Labels: approved

#36 add remove controller and fix other problem in cart
  server/src/controller/cart/addCart.js
  server/src/controller/cart/getCart.js
  server/src/controller/cart/getTotalPriceItems.js
  server/src/controller/cart/removeProduct.js
  server/src/controller/users/user.controller.js
  server/src/database/query/getT.PForOneCart.js
  server/src/database/query/removeProductFromCart.js
  server/src/database/query/user.query.js
  server/src/router/cart.router.js
  server/src/utilis/auth/auth.js
Labels: waiting-review

#39 create product component and functionality
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/components/Button.jsx
  client/src/components/Input.jsx
  client/src/components/Select.jsx
  client/src/components/TestArea.jsx
  client/src/index.css
  client/src/pages/seller.jsx
  client/src/style/seller.css
Labels: waiting-review

#41 create sidebar component and make style
  client/src/App.jsx
  client/src/components/Card.jsx
  client/src/components/Sidebar.jsx
  client/src/style/Sidebar.css
  client/src/style/card.css
  server/src/database/query/product.query.js
  server/src/database/query/user.query.js
Labels: waiting-review

#46 Cart component
  client/src/App.jsx
  client/src/components/Cart.jsx
  client/src/pages/CartPage.jsx
  client/src/style/cart.css
  server/src/controller/cart/getTotalPriceItems.js
  server/src/database/config/build.sql
Labels: waiting-review

#45 28 create navbar component
  client/index.html
  client/src/App.jsx
  client/src/components/Navbar.jsx
  client/src/index.css
  client/src/pages/Home.jsx
  server/src/controller/products/filterProductsByPriceController.js
  server/src/controller/products/getAllProductsController.js
  server/src/database/query/filterPRoductsByPriceQuery.js
  server/src/database/query/getAllProductsQuery.js
  server/src/database/query/product.query.js
  server/src/database/query/user.query.js
Labels: بطيخ

#48 handle forms
  client/src/App.jsx
  client/src/index.css
  client/src/pages/Signin.jsx
  client/src/pages/Signup.jsx
  server/src/database/query/user.query.js
Labels: اعملو ريفيو

#57 Edit server schema for cart
  server/src/controller/cart/addCart.js
  server/src/controller/cart/getTotalPriceItems.js
  server/src/database/config/build.sql
  server/src/database/query/addProductToCart.js
  server/src/database/query/getCart.query.js
  server/src/database/query/user.query.js
  server/src/utilis/auth/auth.js
Labels: done

#62 Fix cart component
  client/src/App.jsx
  client/src/components/Cart.jsx
  client/src/style/cart.css
  client/vite.config.js
Labels: done

#65 64 home page handle
  client/src/components/Sidebar.jsx
  client/src/pages/Shop.jsx
  server/src/controller/products/product.js
  server/src/database/query/product.query.js
  server/src/router/product.router.js
Labels: waiting-review

#66 Enable add to cart function in client side
  client/src/components/Details.jsx
Labels: waiting-review

#70 filter products functionality by category
  client/src/App.jsx
  client/src/components/Layout.jsx
  client/src/components/Navbar.jsx
  client/src/components/ShopLayout.jsx
  client/src/components/Sidebar.jsx
  client/src/components/header.jsx
  client/src/pages/Category.jsx
  client/src/pages/Shop.jsx
  client/vite.config.js
  server/src/controller/products/product.js
  server/src/router/product.router.js
Labels: waiting-review

#71 Enable remove product from cart in the client side
  client/src/components/Cart.jsx
  client/src/components/Details.jsx
  client/src/pages/Signup.jsx
  client/src/pages/seller.jsx
  server/src/controller/cart/addCart.js
  server/src/controller/products/product.js
  server/src/controller/users/user.controller.js
  server/src/database/query/getCart.query.js
  server/src/database/query/removeProductFromCart.js
  server/src/utilis/auth/auth.js
Labels: done

#72 68 add home
  client/src/index.css
  client/src/pages/Home.jsx
  server/src/router/product.router.js
Labels: waiting-review

#80 Update product in cart
  client/src/App.jsx
  client/src/components/Cart.jsx
  client/vite.config.js
  server/src/controller/cart/updateQuantityInCart.js
  server/src/database/config/build.sql
  server/src/database/query/updateProductInCart.js
  server/src/router/cart.router.js
Labels: waiting-review

#82 81 add header section
  client/src/components/header.jsx
  client/src/pages/Home.jsx
  client/src/style/header.css
  client/src/style/home.css
  client/vite.config.js
Labels: done

#84 76 style sign up sign in and fix navbar style
  client/src/components/Input.jsx
  client/src/components/Navbar.jsx
  client/src/components/ShopLayout.jsx
  client/src/components/Sidebar.jsx
  client/src/index.css
  client/src/pages/Shop.jsx
  client/src/pages/Signin.jsx
  client/src/pages/Signup.jsx
  client/src/style/navbar.css
  client/src/style/seller.css
  client/src/style/signup.css
Labels: done

#85 83 style home page
  client/src/App.jsx
  client/src/components/Navbar.jsx
  client/src/pages/Home.jsx
  client/src/style/home.css
  client/src/style/nav.css
  client/src/style/navbar.css
  client/src/style/seller.css
  client/src/style/shop.css
Labels: waiting-review

#87 pagination functionality only on all products fetch with paginate pac…
  client/package-lock.json
  client/package.json
  client/src/components/Sidebar.jsx
  client/src/pages/Shop.jsx
  client/src/style/shop.css
Labels: approved

#89 Edit add product to cart function
  client/src/components/Cart.jsx
  client/src/components/Details.jsx
  client/vite.config.js
  server/src/utilis/auth/auth.js
Labels: done

#92 style details product page
  client/src/components/Details.jsx
  client/src/style/details.css
  client/vite.config.js
Labels: done

#94 style cart page
  client/src/components/Cart.jsx
  client/src/style/cart.css
  server/src/database/config/build.sql
Labels: done

#95 Edit home page
  client/src/components/Navbar.jsx
  client/src/components/header.jsx
  client/src/pages/Home.jsx
  client/src/style/header.css
  client/src/style/home.css
  client/src/style/nav.css
  client/src/style/navbar.css
Labels: done

#100 design shop page
  client/src/components/Card.jsx
  client/src/components/Sidebar.jsx
  client/src/index.css
  client/src/pages/Home.jsx
  client/src/pages/Shop.jsx
  client/src/style/Sidebar.css
  client/src/style/card.css
  client/src/style/home.css
  client/src/style/shop.css
Labels: done

#101 handle errors validation
  client/src/pages/Signup.jsx
  package-lock.json
  server/src/controller/users/user.controller.js
Labels: done

#105 handle auth front end and handle validation error in fron end sign in…
  client/src/components/Details.jsx
  client/src/components/Navbar.jsx
  client/src/pages/Signin.jsx
  server/src/controller/users/user.controller.js
Labels: approved

#106 Fix all style problem
  client/src/App.css
  client/src/App.jsx
  client/src/components/Button.jsx
  client/src/components/Card.jsx
  client/src/components/Cart.jsx
  client/src/components/Details.jsx
  client/src/components/Input.jsx
  client/src/components/Layout.jsx
  client/src/components/Navbar.jsx
  client/src/components/Select.jsx
  client/src/components/ShopLayout.jsx
  client/src/components/TestArea.jsx
  client/src/index.css
  client/src/main.jsx
  client/src/pages/Category.jsx
  client/src/pages/Home.jsx
  client/src/pages/ProductDetails.jsx
  client/src/pages/Signup.jsx
  client/src/pages/seller.jsx
  client/src/style/cart.css
  client/src/style/header.css
  client/src/style/home.css
  server/src/controller/cart/updateQuantityInCart.js
  server/src/controller/users/user.controller.js
  server/src/utilis/auth/auth.js
Labels: waiting-review

#107 new package
  client/package-lock.json
  client/package.json
Labels: waiting-review

#111 fix project style and error box and adding log out functionality
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/app.css
  client/src/components/Card.jsx
  client/src/components/Cart.jsx
  client/src/components/Details.jsx
  client/src/components/Footer.jsx
  client/src/components/Layout.jsx
  client/src/components/Navbar.jsx
  client/src/components/Sidebar.jsx
  client/src/components/header.jsx
  client/src/index.css
  client/src/pages/Home.jsx
  client/src/pages/Signin.jsx
  client/src/pages/Signup.jsx
  client/src/style/Sidebar.css
  client/src/style/card.css
  client/src/style/cart.css
  client/src/style/details.css
  client/src/style/header.css
  client/src/style/home.css
  client/src/style/navbar.css
  client/src/style/signup.css
  server/src/controller/users/user.controller.js
  server/src/router/user.router.js
Labels: approved

#112 109 fix project erorr
  .vscode/settings.json
  client/vite.config.js
  package-lock.json
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/database/config/build.sql
Labels: approved

#114 build a production folder
  client/.gitignore
  client/dist/assets/ajax-loader-e7b44c86.gif
  client/dist/assets/index-2d82ed3c.css
  client/dist/assets/index-d7586920.js
  client/dist/assets/slick-12459f22.svg
  client/dist/index.html
  client/dist/vite.svg
Labels: approved
